# Export created sales order to MS Excel

## ABAP-part
ABAP program `ZUCC_ANALYTICS_SDGEN_EXPORT` exports the sales orders of the selected year to a TSV file.
It accesses the CDS-View `c_salesdocumentitemdex` and extracts a fixed list of fields (matching the Python code below).
You might want to save the TSV file in the `data/` folder here for the sake of simplicity.

## Convert downloaded TSV-file to Excel

In [1]:
import pandas as pd

Column list has to match the above mentioned ABAP program.

In [2]:
columns = [
    "salesdocument", "salesdocumentitem"
    , "salesorganization", "distributionchannel", "division"
    , "material", "soldtoparty", "salesdocumentdate", "requesteddeliverydate"
    , "orderquantity", "orderquantityunit", "itemgrossweight", "itemweightunit"
    , "netamount", "transactioncurrency", "taxamount", "costamount", "subtotal1amount"
    , "plant"
]

In [3]:
# ask for filename
import tkinter
from tkinter import filedialog
root = tkinter.Tk()
root.wm_withdraw() # this completely hides the root window
filename = filedialog.askopenfilename(title='Select .tsv file')
root.destroy()

In [4]:
df = pd.read_csv(filename, sep='\t', header=None, names=columns)
df

,salesdocument,salesdocumentitem,salesorganization,distributionchannel,division,material,soldtoparty,salesdocumentdate,requesteddeliverydate,orderquantity,orderquantityunit,itemgrossweight,itemweightunit,netamount,transactioncurrency,taxamount,costamount,subtotal1amount,plant
0,48,10,DN00,WH,AS,FAID1000,141000,20150101,20150101,10.0,EA,120.0,OZ,412.00,EUR,78.28,200.0,400.0,HH00
1,48,20,DN00,WH,AS,CAGE1000,141000,20150101,20150101,11.0,EA,88.0,OZ,203.94,EUR,38.75,99.0,198.0,HH00
2,48,40,DN00,WH,AS,PUMP1000,141000,20150101,20150101,13.0,EA,130.0,OZ,374.92,EUR,71.23,182.0,364.0,HH00
3,48,50,DN00,WH,AS,RKIT1000,141000,20150101,20150101,9.0,EA,108.0,OZ,296.64,EUR,56.36,144.0,288.0,HH00
4,48,60,DN00,WH,BI,ORWN1000,141000,20150101,20150101,9.0,EA,86040.0,G,23175.00,EUR,4403.25,11250.0,22500.0,HH00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,119,40,UE00,WH,AS,KPAD1000,126000,20150112,20150202,10.0,EA,160.0,OZ,727.50,USD,0.00,375.0,750.0,MI00
536,119,50,UE00,WH,AS,CAGE1000,126000,20150112,20150202,16.0,EA,128.0,OZ,279.36,USD,0.00,144.0,288.0,MI00
537,119,70,UE00,WH,AS,RKIT1000,126000,20150112,20150202,12.0,EA,144.0,OZ,372.48,USD,0.00,192.0,384.0,MI00
538,119,90,UE00,WH,BI,PRTR3000,126000,20150112,20150202,12.0,EA,87720.0,G,37248.00,USD,0.00,18000.0,38400.0,MI00
539,119,100,UE00,WH,AS,RHMT1000,126000,20150112,20150202,12.0,EA,120.0,OZ,582.00,USD,0.00,300.0,600.0,MI00

In [5]:
filename.replace('.tsv', '.xlsx')
df.to_excel('../data/2015analytics.xlsx', index=False)