# Export created sales order to MS Excel

## ABAP-part
ABAP program `ZUCC_ANALYTICS_SDGEN_EXPORT` exports the sales orders of the selected year to a TSV file.
It accesses the CDS-View `c_salesdocumentitemdex` and extracts a fixed list of fields (matching the Python code below).
You might want to save the TSV file in the `data/` folder here for the sake of simplicity.

## Convert downloaded TSV-file to Excel

In [3]:
import pandas as pd

Column list has to match the above mentioned ABAP program.

In [4]:
columns = [
    "salesdocument", "salesdocumentitem"
    , "salesorganization", "distributionchannel", "division"
    , "material", "soldtoparty", "salesdocumentdate"
    , "orderquantity", "orderquantityunit", "itemgrossweight", "itemweightunit"
    , "netamount", "transactioncurrency", "taxamount", "costamount", "subtotal1amount"
    , "plant"
]

In [5]:
# ask for filename
import tkinter
from tkinter import filedialog
root = tkinter.Tk()
root.wm_withdraw() # this completely hides the root window
filename = filedialog.askopenfilename(title='Select .tsv file')
root.destroy()

In [6]:
df = pd.read_csv(filename, sep='\t', header=None, names=columns)
df

,salesdocument,salesdocumentitem,salesorganization,distributionchannel,division,material,soldtoparty,salesdocumentdate,orderquantity,orderquantityunit,itemgrossweight,itemweightunit,netamount,transactioncurrency,taxamount,costamount,subtotal1amount,plant
0,48,10,DN00,WH,AS,FAID1000,141000,20150101,10.0,EA,120.0,OZ,412.00,EUR,78.28,200.0,400.0,HH00
1,48,20,DN00,WH,AS,CAGE1000,141000,20150101,11.0,EA,88.0,OZ,203.94,EUR,38.75,99.0,198.0,HH00
2,48,40,DN00,WH,AS,PUMP1000,141000,20150101,13.0,EA,130.0,OZ,374.92,EUR,71.23,182.0,364.0,HH00
3,48,50,DN00,WH,AS,RKIT1000,141000,20150101,9.0,EA,108.0,OZ,296.64,EUR,56.36,144.0,288.0,HH00
4,48,60,DN00,WH,BI,ORWN1000,141000,20150101,9.0,EA,86040.0,G,23175.00,EUR,4403.25,11250.0,22500.0,HH00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,115,20,UE00,WH,AS,CAGE1000,128000,20150109,13.0,EA,104.0,OZ,241.02,USD,0.00,117.0,234.0,MI00
521,115,30,UE00,WH,AS,PUMP1000,128000,20150109,14.0,EA,140.0,OZ,403.76,USD,0.00,196.0,392.0,MI00
522,115,40,UE00,WH,AS,SHRT1000,128000,20150109,10.0,EA,160.0,OZ,309.00,USD,0.00,150.0,300.0,MI00
523,115,70,UE00,WH,AS,FAID1000,128000,20150109,12.0,EA,144.0,OZ,494.40,USD,0.00,240.0,480.0,MI00
524,115,80,UE00,WH,BI,ORMN1000,128000,20150109,12.0,EA,113520.0,G,29664.00,USD,0.00,14400.0,28800.0,MI00

In [7]:
filename.replace('.tsv', '.xlsx')
df.to_excel('../data/2015analytics.xlsx', index=False)