# Export created sales order to MS Excel

## ABAP-part
ABAP program `ZUCC_ANALYTICS_SDGEN_EXPORT` exports the sales orders of the selected year to a TSV file.
It accesses the CDS-View `c_salesdocumentitemdex` and extracts a fixed list of fields (matching the Python code below).
You might want to save the TSV file in the `data/` folder here for the sake of simplicity.

## Convert downloaded TSV-file to Excel

In [39]:
import pandas as pd

Column list has to match the above mentioned ABAP program.

In [40]:
columns = [
    "SALESDOCUMENT", "SALESDOCUMENTITEM"
    , "SALESORGANIZATION", "DISTRIBUTIONCHANNEL", "DIVISION"
    , "MATERIAL", "SOLDTOPARTY", "SALESDOCUMENTDATE", "REQUESTEDDELIVERYDATE"
    , "ORDERQUANTITY", "ORDERQUANTITYUNIT", "ITEMGROSSWEIGHT", "ITEMWEIGHTUNIT"
    , "NETAMOUNT", "TRANSACTIONCURRENCY", "TAXAMOUNT", "COSTAMOUNT", "SUBTOTAL1AMOUNT"
    , "PLANT"
]

In [41]:
# ask for filename
import tkinter
from tkinter import filedialog
root = tkinter.Tk()
root.wm_withdraw() # this completely hides the root window
filename = filedialog.askopenfilename(title='Select .tsv file')
root.destroy()

In [42]:
df = pd.read_csv(
    filename
    , sep='\t', header=None, names=columns
    # we stay with SAP date format YYYYMMDD as string
    #, parse_dates=["salesdocumentdate", "requesteddeliverydate"], infer_datetime_format=True
    )
df

,SALESDOCUMENT,SALESDOCUMENTITEM,SALESORGANIZATION,DISTRIBUTIONCHANNEL,DIVISION,MATERIAL,SOLDTOPARTY,SALESDOCUMENTDATE,REQUESTEDDELIVERYDATE,ORDERQUANTITY,ORDERQUANTITYUNIT,ITEMGROSSWEIGHT,ITEMWEIGHTUNIT,NETAMOUNT,TRANSACTIONCURRENCY,TAXAMOUNT,COSTAMOUNT,SUBTOTAL1AMOUNT,PLANT
0,2805,60,UE00,WH,AS,GRWL2000,127000,20170102,20170306,9.0,EA,1800.0,G,3473.67,USD,0.0,0.0,3581.1,MI00
1,2805,90,UE00,WH,AS,GRWL2000,127000,20170102,20170306,9.0,EA,1800.0,G,3473.67,USD,0.0,0.0,3581.1,MI00
2,2807,40,UE00,WH,AS,GRWL2000,135000,20170102,20170213,9.0,EA,1800.0,G,3473.67,USD,0.0,0.0,3581.1,MI00
3,2811,40,UE00,WH,AS,GRBL2000,126000,20170102,20170116,9.0,EA,1800.0,G,3473.67,USD,0.0,0.0,3581.1,MI00
4,2811,70,UE00,WH,AS,GRRL2000,126000,20170102,20170116,7.0,EA,1400.0,G,2701.74,USD,0.0,0.0,2785.3,MI00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25220,5412,60,UE00,WH,AS,GRWL2000,126000,20171229,20180323,6.0,EA,1200.0,G,2315.78,USD,0.0,0.0,2387.4,MI00
25221,5412,70,UE00,WH,AS,GRRL2000,126000,20171229,20180323,5.0,EA,1000.0,G,1929.81,USD,0.0,0.0,1989.5,MI00
25222,5412,80,UE00,WH,BI,PRTR1000,126000,20171229,20180323,6.0,EA,43860.0,G,22451.81,USD,0.0,8307.6,23146.2,MI00
25223,5412,90,UE00,WH,AS,RKIT1000,126000,20171229,20180323,6.0,EA,72.0,OZ,224.65,USD,0.0,118.8,231.6,MI00
25224,5412,100,UE00,WH,BI,ORWN1000,126000,20171229,20180323,6.0,EA,57360.0,G,17540.32,USD,0.0,7417.8,18082.8,MI00

In [43]:
xls_file = filename.replace('.tsv', '.xlsx')
df.to_excel(xls_file, index=False)