# Export created sales order to MS Excel

## ABAP-part
ABAP program `ZUCC_ANALYTICS_SDGEN_EXPORT` exports the sales orders of the selected year to a TSV file.
It accesses the CDS-View `c_salesdocumentitemdex` and extracts a fixed list of fields (matching the Python code below).
You might want to save the TSV file in the `data/` folder here for the sake of simplicity.

## Convert downloaded TSV-file to Excel

In [19]:
import pandas as pd

Column list has to match the above mentioned ABAP program.

In [20]:
columns = [
    "SALESDOCUMENT", "SALESDOCUMENTITEM"
    , "SALESORGANIZATION", "DISTRIBUTIONCHANNEL", "DIVISION"
    , "MATERIAL", "SOLDTOPARTY", "SALESDOCUMENTDATE", "REQUESTEDDELIVERYDATE"
    , "ORDERQUANTITY", "ORDERQUANTITYUNIT", "ITEMGROSSWEIGHT", "ITEMWEIGHTUNIT"
    , "NETAMOUNT", "TRANSACTIONCURRENCY", "TAXAMOUNT", "COSTAMOUNT", "SUBTOTAL1AMOUNT"
    , "PLANT"
]

In [21]:
# ask for filename
import tkinter
from tkinter import filedialog
root = tkinter.Tk()
root.wm_withdraw() # this completely hides the root window
filename = filedialog.askopenfilename(title='Select .tsv file')
root.destroy()

In [22]:
df = pd.read_csv(
    filename
    , sep='\t', header=None, names=columns
    # we stay with SAP date format YYYYMMDD as string
    #, parse_dates=["salesdocumentdate", "requesteddeliverydate"], infer_datetime_format=True
    )
df

,SALESDOCUMENT,SALESDOCUMENTITEM,SALESORGANIZATION,DISTRIBUTIONCHANNEL,DIVISION,MATERIAL,SOLDTOPARTY,SALESDOCUMENTDATE,REQUESTEDDELIVERYDATE,ORDERQUANTITY,ORDERQUANTITYUNIT,ITEMGROSSWEIGHT,ITEMWEIGHTUNIT,NETAMOUNT,TRANSACTIONCURRENCY,TAXAMOUNT,COSTAMOUNT,SUBTOTAL1AMOUNT,PLANT
0,17805,10,UE00,WH,AS,CAGE1000,135000,20230208,20230308,17.0,EA,136.0,OZ,366.08,USD,0.00,188.7,377.4,MI00
1,17805,20,UE00,WH,AS,RKIT1000,135000,20230208,20230308,13.0,EA,156.0,OZ,498.09,USD,0.00,256.1,513.5,MI00
2,17805,30,UE00,WH,BI,DXTR2000,135000,20230208,20230308,15.0,EA,127650.0,G,53819.01,USD,0.00,19419.0,55483.5,MI00
3,17805,40,UE00,WH,AS,DGRW2000,135000,20230208,20230308,11.0,EA,2200.0,G,5131.20,USD,0.00,2643.3,5289.9,MI00
4,17805,50,UE00,WH,AS,OHMT1000,135000,20230208,20230308,13.0,EA,195.0,OZ,778.04,USD,0.00,400.4,802.1,MI00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3494,17804,50,DN00,WH,AS,EPAD1000,141000,20230207,20230214,11.0,EA,352.0,OZ,925.09,EUR,175.77,477.4,953.7,HH00
3495,17804,60,DN00,WH,AS,GRBL2000,141000,20230207,20230214,13.0,EA,2600.0,G,4810.71,EUR,914.03,2479.1,4959.5,HH00
3496,17804,70,DN00,WH,BI,ORMN1000,141000,20230207,20230214,15.0,EA,141900.0,G,40363.15,EUR,7669.00,16645.5,41611.5,HH00
3497,17804,80,DN00,WH,BI,ORWN1000,141000,20230207,20230214,13.0,EA,124280.0,G,36439.12,EUR,6923.43,15026.7,37566.1,HH00
3498,17804,90,DN00,WH,AS,PUMP1000,141000,20230207,20230214,19.0,EA,190.0,OZ,597.13,EUR,113.45,305.9,615.6,HH00

In [23]:
# Remove trailing whitespace
df["MATERIAL"] = df["MATERIAL"].str.strip()
df["ORDERQUANTITYUNIT"] = df["ORDERQUANTITYUNIT"].str.strip()
df["ITEMWEIGHTUNIT"] = df["ITEMWEIGHTUNIT"].str.strip()
df["TRANSACTIONCURRENCY"] = df["TRANSACTIONCURRENCY"].str.strip()

In [24]:
xls_file = filename.replace('.tsv', '.xlsx')
df.to_excel(xls_file, index=False)